FROM node:16-alpine

ENV PORT=$PORT
ENV NODE_ENV=$NODE_ENV
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_DATABASE=$DB_DATABASE

WORKDIR /app

COPY package.json /app

RUN npm install

COPY .. /app

EXPOSE $PORT

CMD [ "npm", "run", "start:dev" ]