version: '3.7'
services:
  api:
    container_name: api-container
    build:
      context: .
    depends_on:
      - redis
    links:
      - redis
    command: npm run start:dev
    volumes:
      - '.:/app'
      - 'modules:/app/node_modules'
    ports:
      - '$PORT:$PORT'
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
volumes: 
  modules: